// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1pHZyF5ofMIUv0N7S79DcXgJsGP_jos',
    appId: '1:109039487684:web:13c5be271f295a729dd791',
    messagingSenderId: '109039487684',
    projectId: 'fir-flutter-codelab-4f402',
    authDomain: 'fir-flutter-codelab-4f402.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4f402.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDigky6J8ap-uIL9UgwjMQ5ErpmKw77uGU',
    appId: '1:109039487684:android:208991f3cd52c9299dd791',
    messagingSenderId: '109039487684',
    projectId: 'fir-flutter-codelab-4f402',
    storageBucket: 'fir-flutter-codelab-4f402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUzt4ZS8PlTIpykT3XvmtA3z_-WqaFWi0',
    appId: '1:109039487684:ios:7ea743ba9cf104259dd791',
    messagingSenderId: '109039487684',
    projectId: 'fir-flutter-codelab-4f402',
    storageBucket: 'fir-flutter-codelab-4f402.appspot.com',
    iosClientId: '109039487684-h3lpb7dcbk5v4p95k0bj11loiqmth0be.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUzt4ZS8PlTIpykT3XvmtA3z_-WqaFWi0',
    appId: '1:109039487684:ios:7ea743ba9cf104259dd791',
    messagingSenderId: '109039487684',
    projectId: 'fir-flutter-codelab-4f402',
    storageBucket: 'fir-flutter-codelab-4f402.appspot.com',
    iosClientId: '109039487684-h3lpb7dcbk5v4p95k0bj11loiqmth0be.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}
